/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Type {
  'id' : bigint,
  'patientId' : bigint,
  'submittedAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export interface Type__1 {
  'id' : bigint,
  'status' : string,
  'patientId' : bigint,
  'createdAt' : Time,
  'referredTo' : string,
  'notes' : string,
  'patientName' : string,
  'priority' : string,
  'reason' : string,
}
export interface Type__10 {
  'id' : bigint,
  'content' : string,
  'patientId' : bigint,
  'authorId' : bigint,
  'noteType' : string,
}
export interface Type__11 {
  'id' : bigint,
  'status' : string,
  'serviceDate' : string,
  'diagnosisCodes' : string,
  'patientId' : bigint,
  'submittedAt' : Time,
  'insurerId' : bigint,
  'cptCodes' : string,
  'totalAmount' : bigint,
  'patientName' : string,
  'claimNumber' : string,
}
export interface Type__12 {
  'id' : bigint,
  'relationship' : string,
  'patientId' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'permissionsJson' : string,
}
export interface Type__13 {
  'id' : bigint,
  'action' : string,
  'actorId' : Principal,
  'entityId' : bigint,
  'timestamp' : Time,
  'entityType' : string,
}
export interface Type__14 {
  'id' : bigint,
  'status' : string,
  'patientId' : bigint,
  'date' : string,
  'providerId' : bigint,
}
export interface Type__15 {
  'id' : bigint,
  'patientId' : bigint,
  'severity' : string,
  'allergen' : string,
  'reaction' : string,
}
export interface Type__2 {
  'id' : bigint,
  'status' : string,
  'prescribedBy' : string,
  'patientId' : bigint,
  'medication' : string,
  'dose' : string,
  'createdAt' : Time,
  'notes' : string,
  'patientName' : string,
}
export interface Type__3 {
  'id' : bigint,
  'mrn' : string,
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Type__4 {
  'id' : bigint,
  'content' : string,
  'toUserId' : bigint,
  'fromUserId' : bigint,
}
export interface Type__5 {
  'id' : bigint,
  'scoresJson' : string,
  'patientId' : bigint,
  'date' : string,
  'assessmentType' : string,
  'totalScore' : bigint,
  'notes' : string,
  'severity' : string,
  'providerId' : bigint,
}
export interface Type__6 {
  'id' : bigint,
  'status' : string,
  'patientId' : bigint,
  'dose' : string,
  'name' : string,
  'frequency' : string,
}
export interface Type__7 {
  'id' : bigint,
  'result' : string,
  'isCritical' : boolean,
  'patientId' : bigint,
  'testName' : string,
  'unit' : string,
}
export interface Type__8 {
  'id' : bigint,
  'status' : string,
  'patientId' : bigint,
  'amount' : bigint,
}
export interface Type__9 {
  'id' : bigint,
  'status' : string,
  'patientId' : bigint,
  'createdAt' : Time,
  'orderedBy' : string,
  'modality' : string,
  'indication' : string,
  'patientName' : string,
  'priority' : string,
  'bodyPart' : string,
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface InboxResult {
  'id': bigint,
  'patientId': bigint,
  'testName': string,
  'result': string,
  'isCritical': boolean,
  'acknowledged': boolean,
  'note': string,
  'callbackLogged': boolean,
  'forwardedTo': string,
  'timestamp': Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAllergy' : ActorMethod<[bigint, string, string, string], bigint>,
  'addCaregiver' : ActorMethod<[Type__12], bigint>,
  'addLabResult' : ActorMethod<
    [bigint, string, string, string, boolean],
    bigint
  >,
  'addMedication' : ActorMethod<
    [bigint, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[bigint, bigint, string], bigint>,
  'createClaim' : ActorMethod<
    [bigint, string, string, bigint, bigint, string, string, string],
    bigint
  >,
  'createClinicalNote' : ActorMethod<[bigint, string, string, bigint], bigint>,
  'createImagingOrder' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    bigint
  >,
  'createInvoice' : ActorMethod<[bigint, bigint, string], bigint>,
  'createMentalHealthAssessment' : ActorMethod<[Type__5], bigint>,
  'createPatient' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createPrescription' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'createReferral' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllergies' : ActorMethod<[], Array<Type__15>>,
  'listAppointments' : ActorMethod<[], Array<Type__14>>,
  'listAuditLogs' : ActorMethod<[], Array<Type__13>>,
  'listCaregivers' : ActorMethod<[], Array<Type__12>>,
  'listClaims' : ActorMethod<[], Array<Type__11>>,
  'listClinicalNotes' : ActorMethod<[], Array<Type__10>>,
  'listImagingOrders' : ActorMethod<[], Array<Type__9>>,
  'listInvoices' : ActorMethod<[], Array<Type__8>>,
  'listLabResults' : ActorMethod<[], Array<Type__7>>,
  'listMedications' : ActorMethod<[], Array<Type__6>>,
  'listMentalHealthAssessments' : ActorMethod<[], Array<Type__5>>,
  'listMessages' : ActorMethod<[], Array<Type__4>>,
  'listPatients' : ActorMethod<[], Array<Type__3>>,
  'listPrescriptions' : ActorMethod<[], Array<Type__2>>,
  'listReferrals' : ActorMethod<[], Array<Type__1>>,
  'listSurveyResponses' : ActorMethod<[], Array<Type>>,
  'removeCaregiver' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSurveyResponse' : ActorMethod<[Type], bigint>,
  'sendMessage' : ActorMethod<[bigint, bigint, string], bigint>,
  'updateAppointmentStatus' : ActorMethod<[bigint, string], boolean>,
  'updateClaimStatus' : ActorMethod<[bigint, string], boolean>,
  'updateImagingOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateInvoiceStatus' : ActorMethod<[bigint, string], boolean>,
  'updateMedicationStatus' : ActorMethod<[bigint, string], boolean>,
  'updatePatient' : ActorMethod<
    [bigint, string, string, string, string],
    boolean
  >,
  'updatePrescriptionStatus' : ActorMethod<[bigint, string], boolean>,
  'updateReferralStatus' : ActorMethod<[bigint, string], boolean>,
  'listInboxResults': ActorMethod<[], Array<InboxResult>>,
  'acknowledgeResult': ActorMethod<[bigint], boolean>,
  'saveResultNote': ActorMethod<[bigint, string], boolean>,
  'saveResultCallback': ActorMethod<[bigint, string, string, string], boolean>,
  'forwardResult': ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];