/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type__12 = IDL.Record({
  'id' : IDL.Nat,
  'relationship' : IDL.Text,
  'patientId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'permissionsJson' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type__5 = IDL.Record({
  'id' : IDL.Nat,
  'scoresJson' : IDL.Text,
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'assessmentType' : IDL.Text,
  'totalScore' : IDL.Int,
  'notes' : IDL.Text,
  'severity' : IDL.Text,
  'providerId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Type__15 = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'severity' : IDL.Text,
  'allergen' : IDL.Text,
  'reaction' : IDL.Text,
});
export const Type__14 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'providerId' : IDL.Nat,
});
export const Time = IDL.Int;
export const Type__13 = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'actorId' : IDL.Principal,
  'entityId' : IDL.Nat,
  'timestamp' : Time,
  'entityType' : IDL.Text,
});
export const Type__11 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceDate' : IDL.Text,
  'diagnosisCodes' : IDL.Text,
  'patientId' : IDL.Nat,
  'submittedAt' : Time,
  'insurerId' : IDL.Nat,
  'cptCodes' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'patientName' : IDL.Text,
  'claimNumber' : IDL.Text,
});
export const Type__10 = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'patientId' : IDL.Nat,
  'authorId' : IDL.Nat,
  'noteType' : IDL.Text,
});
export const Type__9 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'orderedBy' : IDL.Text,
  'modality' : IDL.Text,
  'indication' : IDL.Text,
  'patientName' : IDL.Text,
  'priority' : IDL.Text,
  'bodyPart' : IDL.Text,
});
export const Type__8 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'patientId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Type__7 = IDL.Record({
  'id' : IDL.Nat,
  'result' : IDL.Text,
  'isCritical' : IDL.Bool,
  'patientId' : IDL.Nat,
  'testName' : IDL.Text,
  'unit' : IDL.Text,
});
export const Type__6 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'patientId' : IDL.Nat,
  'dose' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const Type__4 = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'toUserId' : IDL.Nat,
  'fromUserId' : IDL.Nat,
});
export const Type__3 = IDL.Record({
  'id' : IDL.Nat,
  'mrn' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Type__2 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'prescribedBy' : IDL.Text,
  'patientId' : IDL.Nat,
  'medication' : IDL.Text,
  'dose' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
});
export const Type__1 = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'referredTo' : IDL.Text,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'priority' : IDL.Text,
  'reason' : IDL.Text,
});
export const Type = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'submittedAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAllergy' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addCaregiver' : IDL.Func([Type__12], [IDL.Nat], []),
  'addLabResult' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addMedication' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createClaim' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createClinicalNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createImagingOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createMentalHealthAssessment' : IDL.Func([Type__5], [IDL.Nat], []),
  'createPatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPrescription' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createReferral' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllergies' : IDL.Func([], [IDL.Vec(Type__15)], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(Type__14)], ['query']),
  'listAuditLogs' : IDL.Func([], [IDL.Vec(Type__13)], ['query']),
  'listCaregivers' : IDL.Func([], [IDL.Vec(Type__12)], ['query']),
  'listClaims' : IDL.Func([], [IDL.Vec(Type__11)], ['query']),
  'listClinicalNotes' : IDL.Func([], [IDL.Vec(Type__10)], ['query']),
  'listImagingOrders' : IDL.Func([], [IDL.Vec(Type__9)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Type__8)], ['query']),
  'listLabResults' : IDL.Func([], [IDL.Vec(Type__7)], ['query']),
  'listMedications' : IDL.Func([], [IDL.Vec(Type__6)], ['query']),
  'listMentalHealthAssessments' : IDL.Func([], [IDL.Vec(Type__5)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(Type__4)], ['query']),
  'listPatients' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
  'listPrescriptions' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
  'listReferrals' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
  'listSurveyResponses' : IDL.Func([], [IDL.Vec(Type)], ['query']),
  'removeCaregiver' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSurveyResponse' : IDL.Func([Type], [IDL.Nat], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateClaimStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateImagingOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateInvoiceStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateMedicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updatePatient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePrescriptionStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateReferralStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type__12 = IDL.Record({
    'id' : IDL.Nat,
    'relationship' : IDL.Text,
    'patientId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'permissionsJson' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type__5 = IDL.Record({
    'id' : IDL.Nat,
    'scoresJson' : IDL.Text,
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'assessmentType' : IDL.Text,
    'totalScore' : IDL.Int,
    'notes' : IDL.Text,
    'severity' : IDL.Text,
    'providerId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Type__15 = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'severity' : IDL.Text,
    'allergen' : IDL.Text,
    'reaction' : IDL.Text,
  });
  const Type__14 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'providerId' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Type__13 = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'actorId' : IDL.Principal,
    'entityId' : IDL.Nat,
    'timestamp' : Time,
    'entityType' : IDL.Text,
  });
  const Type__11 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceDate' : IDL.Text,
    'diagnosisCodes' : IDL.Text,
    'patientId' : IDL.Nat,
    'submittedAt' : Time,
    'insurerId' : IDL.Nat,
    'cptCodes' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'patientName' : IDL.Text,
    'claimNumber' : IDL.Text,
  });
  const Type__10 = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'patientId' : IDL.Nat,
    'authorId' : IDL.Nat,
    'noteType' : IDL.Text,
  });
  const Type__9 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'orderedBy' : IDL.Text,
    'modality' : IDL.Text,
    'indication' : IDL.Text,
    'patientName' : IDL.Text,
    'priority' : IDL.Text,
    'bodyPart' : IDL.Text,
  });
  const Type__8 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'patientId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Type__7 = IDL.Record({
    'id' : IDL.Nat,
    'result' : IDL.Text,
    'isCritical' : IDL.Bool,
    'patientId' : IDL.Nat,
    'testName' : IDL.Text,
    'unit' : IDL.Text,
  });
  const Type__6 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'patientId' : IDL.Nat,
    'dose' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const Type__4 = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'toUserId' : IDL.Nat,
    'fromUserId' : IDL.Nat,
  });
  const Type__3 = IDL.Record({
    'id' : IDL.Nat,
    'mrn' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Type__2 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'prescribedBy' : IDL.Text,
    'patientId' : IDL.Nat,
    'medication' : IDL.Text,
    'dose' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
  });
  const Type__1 = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'referredTo' : IDL.Text,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'priority' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Type = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'submittedAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAllergy' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addCaregiver' : IDL.Func([Type__12], [IDL.Nat], []),
    'addLabResult' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addMedication' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createClaim' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createClinicalNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createImagingOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createMentalHealthAssessment' : IDL.Func([Type__5], [IDL.Nat], []),
    'createPatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPrescription' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createReferral' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllergies' : IDL.Func([], [IDL.Vec(Type__15)], ['query']),
    'listAppointments' : IDL.Func([], [IDL.Vec(Type__14)], ['query']),
    'listAuditLogs' : IDL.Func([], [IDL.Vec(Type__13)], ['query']),
    'listCaregivers' : IDL.Func([], [IDL.Vec(Type__12)], ['query']),
    'listClaims' : IDL.Func([], [IDL.Vec(Type__11)], ['query']),
    'listClinicalNotes' : IDL.Func([], [IDL.Vec(Type__10)], ['query']),
    'listImagingOrders' : IDL.Func([], [IDL.Vec(Type__9)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Type__8)], ['query']),
    'listLabResults' : IDL.Func([], [IDL.Vec(Type__7)], ['query']),
    'listMedications' : IDL.Func([], [IDL.Vec(Type__6)], ['query']),
    'listMentalHealthAssessments' : IDL.Func([], [IDL.Vec(Type__5)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(Type__4)], ['query']),
    'listPatients' : IDL.Func([], [IDL.Vec(Type__3)], ['query']),
    'listPrescriptions' : IDL.Func([], [IDL.Vec(Type__2)], ['query']),
    'listReferrals' : IDL.Func([], [IDL.Vec(Type__1)], ['query']),
    'listSurveyResponses' : IDL.Func([], [IDL.Vec(Type)], ['query']),
    'removeCaregiver' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSurveyResponse' : IDL.Func([Type], [IDL.Nat], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateClaimStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateImagingOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateInvoiceStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateMedicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updatePatient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePrescriptionStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateReferralStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };