/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Type {
    id: bigint;
    patientId: bigint;
    submittedAt: Time;
    comment: string;
    rating: bigint;
}
export interface Type__11 {
    id: bigint;
    status: string;
    serviceDate: string;
    diagnosisCodes: string;
    patientId: bigint;
    submittedAt: Time;
    insurerId: bigint;
    cptCodes: string;
    totalAmount: bigint;
    patientName: string;
    claimNumber: string;
}
export type Time = bigint;
export interface Type__7 {
    id: bigint;
    result: string;
    isCritical: boolean;
    patientId: bigint;
    testName: string;
    unit: string;
}
export interface Type__15 {
    id: bigint;
    patientId: bigint;
    severity: string;
    allergen: string;
    reaction: string;
}
export interface Type__10 {
    id: bigint;
    content: string;
    patientId: bigint;
    authorId: bigint;
    noteType: string;
}
export interface Type__12 {
    id: bigint;
    relationship: string;
    patientId: bigint;
    name: string;
    email: string;
    phone: string;
    permissionsJson: string;
}
export interface Type__6 {
    id: bigint;
    status: string;
    patientId: bigint;
    dose: string;
    name: string;
    frequency: string;
}
export interface Type__2 {
    id: bigint;
    status: string;
    prescribedBy: string;
    patientId: bigint;
    medication: string;
    dose: string;
    createdAt: Time;
    notes: string;
    patientName: string;
}
export interface Type__9 {
    id: bigint;
    status: string;
    patientId: bigint;
    createdAt: Time;
    orderedBy: string;
    modality: string;
    indication: string;
    patientName: string;
    priority: string;
    bodyPart: string;
}
export interface Type__13 {
    id: bigint;
    action: string;
    actorId: Principal;
    entityId: bigint;
    timestamp: Time;
    entityType: string;
}
export interface Type__5 {
    id: bigint;
    scoresJson: string;
    patientId: bigint;
    date: string;
    assessmentType: string;
    totalScore: bigint;
    notes: string;
    severity: string;
    providerId: bigint;
}
export interface Type__3 {
    id: bigint;
    mrn: string;
    dateOfBirth: string;
    name: string;
    email: string;
    phone: string;
}
export interface Type__1 {
    id: bigint;
    status: string;
    patientId: bigint;
    createdAt: Time;
    referredTo: string;
    notes: string;
    patientName: string;
    priority: string;
    reason: string;
}
export interface Type__8 {
    id: bigint;
    status: string;
    patientId: bigint;
    amount: bigint;
}
export interface Type__14 {
    id: bigint;
    status: string;
    patientId: bigint;
    date: string;
    providerId: bigint;
}
export interface Type__4 {
    id: bigint;
    content: string;
    toUserId: bigint;
    fromUserId: bigint;
}
export interface UserProfile {
    userId: bigint;
    name: string;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAllergy(patientId: bigint, allergen: string, reaction: string, severity: string): Promise<bigint>;
    addCaregiver(caregiver: Type__12): Promise<bigint>;
    addLabResult(patientId: bigint, testName: string, result: string, unit: string, isCritical: boolean): Promise<bigint>;
    addMedication(patientId: bigint, name: string, dose: string, frequency: string, status: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(patientId: bigint, providerId: bigint, date: string): Promise<bigint>;
    createClaim(patientId: bigint, patientName: string, claimNumber: string, insurerId: bigint, totalAmount: bigint, serviceDate: string, cptCodes: string, diagnosisCodes: string): Promise<bigint>;
    createClinicalNote(patientId: bigint, noteType: string, content: string, authorId: bigint): Promise<bigint>;
    createImagingOrder(patientId: bigint, patientName: string, modality: string, bodyPart: string, priority: string, orderedBy: string, indication: string): Promise<bigint>;
    createInvoice(patientId: bigint, amount: bigint, status: string): Promise<bigint>;
    createMentalHealthAssessment(assessment: Type__5): Promise<bigint>;
    createPatient(name: string, dob: string, phone: string, email: string, mrn: string): Promise<bigint>;
    createPrescription(patientId: bigint, patientName: string, medication: string, dose: string, prescribedBy: string, notes: string): Promise<bigint>;
    createReferral(patientId: bigint, patientName: string, referredTo: string, reason: string, priority: string, notes: string): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllergies(): Promise<Array<Type__15>>;
    listAppointments(): Promise<Array<Type__14>>;
    listAuditLogs(): Promise<Array<Type__13>>;
    listCaregivers(): Promise<Array<Type__12>>;
    listClaims(): Promise<Array<Type__11>>;
    listClinicalNotes(): Promise<Array<Type__10>>;
    listImagingOrders(): Promise<Array<Type__9>>;
    listInvoices(): Promise<Array<Type__8>>;
    listLabResults(): Promise<Array<Type__7>>;
    listMedications(): Promise<Array<Type__6>>;
    listMentalHealthAssessments(): Promise<Array<Type__5>>;
    listMessages(): Promise<Array<Type__4>>;
    listPatients(): Promise<Array<Type__3>>;
    listPrescriptions(): Promise<Array<Type__2>>;
    listReferrals(): Promise<Array<Type__1>>;
    listSurveyResponses(): Promise<Array<Type>>;
    removeCaregiver(id: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSurveyResponse(response: Type): Promise<bigint>;
    sendMessage(fromUserId: bigint, toUserId: bigint, content: string): Promise<bigint>;
    updateAppointmentStatus(id: bigint, newStatus: string): Promise<boolean>;
    updateClaimStatus(id: bigint, newStatus: string): Promise<boolean>;
    updateImagingOrderStatus(id: bigint, newStatus: string): Promise<boolean>;
    updateInvoiceStatus(id: bigint, newStatus: string): Promise<boolean>;
    updateMedicationStatus(id: bigint, newStatus: string): Promise<boolean>;
    updatePatient(id: bigint, name: string, dob: string, phone: string, email: string): Promise<boolean>;
    updatePrescriptionStatus(id: bigint, newStatus: string): Promise<boolean>;
    updateReferralStatus(id: bigint, newStatus: string): Promise<boolean>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAllergy(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllergy(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllergy(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addCaregiver(arg0: Type__12): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCaregiver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCaregiver(arg0);
            return result;
        }
    }
    async addLabResult(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLabResult(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLabResult(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMedication(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2);
            return result;
        }
    }
    async createClaim(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClaim(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createClinicalNote(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClinicalNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClinicalNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createImagingOrder(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createImagingOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImagingOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2);
            return result;
        }
    }
    async createMentalHealthAssessment(arg0: Type__5): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMentalHealthAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMentalHealthAssessment(arg0);
            return result;
        }
    }
    async createPatient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPrescription(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrescription(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createReferral(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferral(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferral(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllergies(): Promise<Array<Type__15>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllergies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllergies();
            return result;
        }
    }
    async listAppointments(): Promise<Array<Type__14>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return result;
        }
    }
    async listAuditLogs(): Promise<Array<Type__13>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAuditLogs();
            return result;
        }
    }
    async listCaregivers(): Promise<Array<Type__12>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCaregivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCaregivers();
            return result;
        }
    }
    async listClaims(): Promise<Array<Type__11>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClaims();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClaims();
            return result;
        }
    }
    async listClinicalNotes(): Promise<Array<Type__10>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClinicalNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClinicalNotes();
            return result;
        }
    }
    async listImagingOrders(): Promise<Array<Type__9>> {
        if (this.processError) {
            try {
                const result = await this.actor.listImagingOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listImagingOrders();
            return result;
        }
    }
    async listInvoices(): Promise<Array<Type__8>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return result;
        }
    }
    async listLabResults(): Promise<Array<Type__7>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLabResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLabResults();
            return result;
        }
    }
    async listMedications(): Promise<Array<Type__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedications();
            return result;
        }
    }
    async listMentalHealthAssessments(): Promise<Array<Type__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMentalHealthAssessments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMentalHealthAssessments();
            return result;
        }
    }
    async listMessages(): Promise<Array<Type__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMessages();
            return result;
        }
    }
    async listPatients(): Promise<Array<Type__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPatients();
            return result;
        }
    }
    async listPrescriptions(): Promise<Array<Type__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrescriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrescriptions();
            return result;
        }
    }
    async listReferrals(): Promise<Array<Type__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReferrals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReferrals();
            return result;
        }
    }
    async listSurveyResponses(): Promise<Array<Type>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSurveyResponses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSurveyResponses();
            return result;
        }
    }
    async removeCaregiver(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCaregiver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCaregiver(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveSurveyResponse(arg0: Type): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSurveyResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSurveyResponse(arg0);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateClaimStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClaimStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClaimStatus(arg0, arg1);
            return result;
        }
    }
    async updateImagingOrderStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImagingOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImagingOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateInvoiceStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(arg0, arg1);
            return result;
        }
    }
    async updateMedicationStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicationStatus(arg0, arg1);
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePrescriptionStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescriptionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescriptionStatus(arg0, arg1);
            return result;
        }
    }
    async updateReferralStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferralStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferralStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
